### ISSUE TITLE
unable to use already installed Bundler

### ISSUE THREAD

**Issue by italy-portugal** [alienfast/bamboozled-ruby-plugin#15]
I'm running into a problem in that I have the bundler binstub installed in a different directory than the primary ruby executable. ( e.g. `/usr/local/bin/bundle` vs. `/usr/bin/ruby` ). It appears that the plugin assumes both ruby and gem binstubs would exist in the same directory. It would be very nice if the path could be configured or was retrieved from the information listed in `gem env`.

I am using the system ruby and I don't have access to the machine to setup RVM.

**Comment by rosskevin** [comment]
You may submit a PR for this custom functionality around the system ruby, but using system ruby is neither recommended nor a primary focus for a continuous integration application/plugin due to the potential heterogeneous environments needed.

If you want to submit a PR, please leave this open, otherwise close this because we aren't going to invest time in expanding the system ruby feature set without community support.
