### ISSUE TITLE
Ruby Runtime Configuration required (on the Miscellaneous tab)

### ISSUE THREAD

**Issue by Jimflip** [alienfast/bamboozled-ruby-plugin#6]
Some plans show the available RVM ruby environments other don't.
So some plans will work with bamboozled others won't, even if I clone an already existing and working plan, the new plan might not work.

bamboo version 5.7.2 build 5716 - 02 Dec 14

**Comment by rosskevin** [comment]
Please provide a stack trace from the log.  If you have a fix we will also happily accept a pull request.

**Comment by rosskevin** [comment]
@Jimflip I have not heard back from you.  I've added some additional error handling in the upcoming release.  I'm guessing that you are not "detecting server capabilities" and setting your ruby runtime on the miscellaneous tab as described in the instructions.

If you have more information, please add it and reopen this.

**Comment by dexterp** [comment]
I know this is an old ticket but I'm facing similar issues. The Bamboozled plugin is not detecting any capabilities after detecting capabilities. Should I raise another ticket?

**Comment by rosskevin** [comment]
@dexterp your issue appears to be with detection, whereas this issue is unknown.  You should open a new issue at include relevant information from your logs.  You're bamboo version, your plugin version, OS version etc is also useful, in addition to your ruby runtime manager i.e. are you using rvm or something else.
